name: film_sms
description: Professional fake SMS app for film production
publish_to: "none"

version: 1.1.0+2

environment:
  # Dart constraint matches Flutter 3.35.4 (bundled Dart 3.9.x)
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.20.2 # Date/time formatting
  uuid: ^4.0.0 # ID generation
  path_provider: ^2.1.4
  window_manager: ^0.3.9

  # UI - REMOVED material_color_utilities (Flutter provides it automatically)

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  hive_generator: 2.0.1
  build_runner: 2.4.7

  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.0
  rename: 3.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  image_path: "web/icons/Icon-512.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "web/icons/Icon-512.png"
    background_color: "#2D77E7"
    theme_color: "#2D77E7"
  windows:
    generate: true
    image_path: "web/icons/Icon-512.png"
  macos:
    generate: true
    image_path: "web/icons/Icon-512.png"
  linux:
    generate: true
    image_path: "web/icons/Icon-512.png"

flutter_native_splash:
  color: "#2D77E7"
  image: "web/icons/Icon-192.png"
  android: true
  ios: true
  web: true
  android_12:
    color: "#2D77E7"
    image: "web/icons/Icon-192.png"

# Centralized app metadata (reference for tooling/scripts)
app_metadata:
  application_name: "Film SMS"
  android_application_id: "be.jaske.filmsms"
  ios_bundle_identifier: "be.jaske.filmsms"
