name: Flutter CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: 3.35.4

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations (l10n)
        run: flutter gen-l10n

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test

  build-web:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations (l10n)
        run: flutter gen-l10n

      - name: Build Web Release
        run: flutter build web --release --base-href=/film-sms/ --no-wasm-dry-run

      - name: Include .htaccess in build
        run: |
          set -euo pipefail
          if [ ! -f web/.htaccess ]; then
            echo "ERROR: web/.htaccess not found" >&2
            ls -la web || true
            exit 1
          fi
          mkdir -p build/web
          cp -v web/.htaccess build/web/.htaccess
          echo "Listing build/web (showing .htaccess):"
          ls -la build/web | sed -n '1,200p'

      - name: Package Web Artifact (zip including dotfiles)
        run: |
          set -euo pipefail
          cd build/web
          zip -r ../web-release.zip .
          cd -
          ls -lh build/web-release.zip

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web-release.zip
          retention-days: 14

  build-windows:
    runs-on: windows-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations (l10n)
        run: flutter gen-l10n

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
          retention-days: 14

  build-android:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations (l10n)
        run: flutter gen-l10n

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Build Android debug APK
        run: flutter build apk --debug

      - name: Upload Android Artifact (debug APK)
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14
